In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import numpy as np

In [2]:
data = pd.read_csv("Data/industries.csv")

In [3]:
data

     code                                        description
0      11                     Growing of non-perennial crops
1     111  Growing of cereals (except rice), leguminous c...
2     112                                    Growing of rice
3     113  Growing of vegetables and melons, roots and tu...
4     114                              Growing of sugar cane
..    ...                                                ...
882  9810  Undifferentiated goods-producing activities of...
883   982  Undifferentiated service-producing activities ...
884  9820  Undifferentiated service-producing activities ...
885   990  Activities of extraterritorial organisations a...
886  9900  Activities of extraterritorial organisations a...

[887 rows x 2 columns]

In [4]:
comdata = pd.read_json("Data/merger_data.json")

In [5]:
comdata

,date_completion,bidders_name,date_completion_assumed,date_last_status_update,status,bidders_industry,id,comments,targets_industry,targets_isin,date_rumor,date_postponed,date_announcement,bidders_isin,date_completion_expected,date_withdrawn,targets_country,type,targets_name,bidders_country
0,None,[],None,None,Rumour - Expired,[],1601040256,2008-11-26: Federal Property Management Agency...,[0811],[None],2008-11-26,None,None,[],None,None,[RU],Acquisition 100%,[ivanovskoe karyeroupravlenie oao],[]
1,None,[cmc centrozlom sp zoo],None,None,Rumour - Expired,[4672],1601232181,2010-11-10: Polish Treasury Ministry stated th...,[4672],[None],2010-11-10,None,None,[None],None,None,[PL],Acquisition increased from 51% to 92.72%,[scrapena sa],[PL]
2,None,[morningstar japan kk],2010-02-26,None,Completed Assumed,[6312],620622,2008-02-25: it was announced that Morningstar ...,[],[],2008-02-25,None,2008-02-25,[JP3922100007],None,None,[],Acquisition increased from 52.3% to 100%,[],[JP]
3,2023-04-03,[fabryka obrabiarek rafamet sa],None,2023-04-06,Completed,[2849],2007102004,2023-02-15: it was stated that Fabryka Obrabia...,[2451],[None],2023-02-15,None,2023-03-09,[PLRFMET00016],None,None,[PL],Acquisition increased from 100% to 100%,[odlewnia rafamet sp zoo],[PL]
4,2014-04-22,[fabrika kartona umka doo],None,None,Completed,[1712],1909107449,"2014-04-28: it was announced that on 22/04/14,...",[1712],[RSFHBGE53066],2014-04-22,None,2014-04-22,[RSUMKAE56492],None,None,[RS],Acquisition 64.131%,[fabrika hartije doo],[RS]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825768,2004-07-14,[taj gvk hotels and resorts ltd],None,2004-07-14,Completed,[5510],151050,2002-04-26: India Tourism Development Corp (IT...,[],[],2002-04-26,None,2002-05-03,[INE586B01026],None,None,[],Acquisition 100%,[],[IN]
825769,None,[],2021-06-13,None,Completed Assumed,[],1939068111,2019-06-13: it was announced that Biocannabix ...,[2120],[None],2019-06-13,None,2019-06-13,[],None,None,[CO],Acquisition 100%,[lifeline pharma sas],[]
825770,None,[mitutoyo corporation],2013-01-21,None,Completed Assumed,[2651],1633020959,2011-01-21: it was announced that Leeport Mach...,[4669],[None],2011-01-21,None,2011-01-21,[None],None,None,[VG],Acquisition increased from 10% to 51%,[leeport metrology corporation],[JP]
825771,None,[woori technology inc.],2010-04-22,None,Completed Assumed,[2712],1600005445,2008-04-22: it was announced that Woori Techno...,[6201],[None],2008-04-22,None,2008-04-22,[KR7032820003],None,None,[GB],Acquisition increased from 100% to 100%,"[mayhill co., ltd]",[KR]
825772,None,[],None,None,Rumour - Expired,[],1943078399,2018-12-31: it was stated that Energy Internat...,[0910],[None],2018-12-31,None,None,[],None,None,[HK],Acquisition 100%,[china era energy power investment ltd],[]

In [7]:
comdata.describe()

                 id
count  8.257730e+05
mean   1.308088e+09
std    8.362040e+08
min    3.085700e+04
25%    5.684240e+05
50%    1.633051e+09
75%    1.941122e+09
max    2.007601e+09

In [8]:
comdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825773 entries, 0 to 825772
Data columns (total 20 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   date_completion           506135 non-null  object
 1   bidders_name              825773 non-null  object
 2   date_completion_assumed   161144 non-null  object
 3   date_last_status_update   175350 non-null  object
 4   status                    825773 non-null  object
 5   bidders_industry          825773 non-null  object
 6   id                        825773 non-null  int64
 7   comments                  825773 non-null  object
 8   targets_industry          825773 non-null  object
 9   targets_isin              825773 non-null  object
 10  date_rumor                825773 non-null  object
 11  date_postponed            214 non-null     object
 12  date_announcement         696242 non-null  object
 13  bidders_isin              825773 non-null  object
 14  date_completion_expected  41758 non-null   object
 15  date_withdrawn            16469 non-null   object
 16  targets_country           825773 non-null  object
 17  type                      825773 non-null  object
 18  targets_name              825773 non-null  object
 19  bidders_country           825773 non-null  object
dtypes: int64(1), object(19)
memory usage: 126.0+ MB